# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    ens3:
      dhcp4: no
      addresses: [13.13.13.25/24]
      gateway4: 13.13.13.1
      nameservers:
              addresses: [13.13.13.53]
